---
title: 'Class12: Homework'
author: "Rachel Lamm (A18518313)"
date: "2026-02-16"
output: pdf_document
---

> Q13: Read this file into R and determine the sample size for each genotype and their corresponding median expression levels for each of these genotypes. 

```{r}
data <- read.table("rs8067378_ENSG00000172057.6.txt", header=TRUE)
```

```{r}
table(data$geno)
```

```{r}
summary(data$exp[data$geno=="A/A"])
summary(data$exp[data$geno=="A/G"])
summary(data$exp[data$geno=="G/G"])

```

```{r}
bp <- boxplot(exp ~ geno, data=data)
```
```{r}
bp$stats[3,]
```

>Q14: Generate a boxplot with a box per genotype, what could you infer from the relative expression value between A/A and G/G displayed in this plot? Does the SNP effect the expression of ORMDL3?

```{r}
boxplot(exp ~ geno, data=data,
        main="ORMDL3 Expression by Genotype",
        xlab="Genotype",
        ylab="Relative Expression",
        col=c("lightblue", "lightgreen", "pink"))

stripchart(exp ~ geno,
           data=data,
           method="jitter",
           pch=16,
           col=rgb(0,0,0,0.5),
           vertical=TRUE,
           add=TRUE)
```


